/* Generated By:JJTree: Do not edit this line. ASTElseIfThen.java */
package jigcell.sbml2.jep;

public class ASTElseIfThen extends SimpleNode {
   public ASTElseIfThen (int id) {
      super (id);
   }

   public ASTElseIfThen (Parser p, int id) {
      super (p, id);
   }

   /**
    * Accept the visitor.
    */

   public Object jjtAccept (ParserVisitor visitor, Object data) {
      return visitor.visit (this, data);
   }
}
