/* Generated By:JJTree: Do not edit this line. ASTElse.java */
package jigcell.sbml2.jep;

public class ASTElse extends SimpleNode {
   public ASTElse (int id) {
      super (id);
   }

   public ASTElse (Parser p, int id) {
      super (p, id);
   }

   /**
    * Accept the visitor.
    */

   public Object jjtAccept (ParserVisitor visitor, Object data) {
      return visitor.visit (this, data);
   }
}
