/* Generated By:JJTree: Do not edit this line. ASTPiecewise.java */
package jigcell.sbml2.jep;

public class ASTPiecewise extends SimpleNode {
   public ASTPiecewise (int id) {
      super (id);
   }

   public ASTPiecewise (Parser p, int id) {
      super (p, id);
   }

   /**
    * Accept the visitor.
    */

   public Object jjtAccept (ParserVisitor visitor, Object data) {
      return visitor.visit (this, data);
   }
}
