/* Generated By:JJTree: Do not edit this line. ParserTreeConstants.java */
package jigcell.sbml2.jep;

public interface ParserTreeConstants {
   String jjtNodeName [] = {"Start", "void", "FunNode", "VarNode", "IfThen", "ElseIfThen", "Else", "Piecewise", "Constant",};
   int JJTCONSTANT = 8;
   int JJTELSE = 6;
   int JJTELSEIFTHEN = 5;
   int JJTFUNNODE = 2;
   int JJTIFTHEN = 4;
   int JJTPIECEWISE = 7;
   int JJTSTART = 0;
   int JJTVARNODE = 3;
   int JJTVOID = 1;
}
