/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package jigcell.sbml2.jep;

public interface ParserConstants {
   String tokenImage [] = {
      "<EOF>", "\" \"", "\"\\t\"", "\"\\n\"", "\"\\r\"", "<INTEGER_LITERAL>", "<DECIMAL_LITERAL>", "<FLOATING_POINT_LITERAL>", "<EXPONENT>",
      "\"\\\\\"", "\">\"", "\"<\"", "\"=\"", "\"<=\"", "\">=\"", "\"!=\"", "\"AND\"", "\"OR\"", "\"XOR\"", "\"NOT\"", "\"+\"", "\"-\"", "\"*\"",
      "\"/\"", "\"^\"", "\"if\"", "\"elseif\"", "\"else\"", "\"then\"", "\"true\"", "\"false\"", "<IDENTIFIER>", "<LETTER>", "<DIGIT>", "<ESC>",
      "\"(\"", "\")\"", "\",\"",
   };
   int AND = 16;
   int DECIMAL_LITERAL = 6;
   int DEFAULT = 0;
   int DIGIT = 33;
   int DIV = 23;
   int ELSE = 27;
   int ELSEIF = 26;
   int EOF = 0;
   int EQ = 12;
   int ESC = 34;
   int ESCAP = 9;
   int EXPONENT = 8;
   int FALSE = 30;
   int FLOATING_POINT_LITERAL = 7;
   int GE = 14;
   int GT = 10;
   int IDENTIFIER = 31;
   int IF = 25;
   int INTEGER_LITERAL = 5;
   int LE = 13;
   int LETTER = 32;
   int LT = 11;
   int MINUS = 21;
   int MUL = 22;
   int NE = 15;
   int NOT = 19;
   int OR = 17;
   int PLUS = 20;
   int POWER = 24;
   int THEN = 28;
   int TRUE = 29;
   int XOR = 18;
}
